name: base_pm2
description: A base application.


publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  cached_network_image: ^3.0.0
  cr_calendar: ^0.0.10
  #c
  country_picker: ^2.0.15
  collection: ^1.15.0

  dio_http_cache: any

  #p
  pull_to_refresh: ^2.0.0
  permission_handler: ^8.3.0
  pinput: ^2.2.11
  path_provider: ^2.0.11

  #e
  expandable: ^5.0.1

  #f
  fluttertoast: ^8.0.7
  flutter_svg: any
  firebase_core: ^1.19.1
  firebase_messaging: ^11.2.0
  firebase_remote_config: ^2.0.0
  flutter_local_notifications: ^9.5.3+1
  flutter_html: ^2.2.1
  flutter_typeahead: ^3.2.1
  flutter_native_splash: ^2.1.6
  flutter_dialogs: ^2.1.1
  flutter_spinkit: ^5.1.0

  #n
  numberpicker: ^2.1.1

  #l
  local_auth: ^2.1.0
  #r
  retrofit: any

  #s1
  shared_preferences: ^2.0.15
  syncfusion_flutter_datepicker: ^19.3.56
  syncfusion_flutter_charts: ^19.3.56

  #i
  intl: ^0.17.0
  image_picker: ^0.8.5
  intl_phone_field: ^3.1.0

  #g
  get: ^4.6.0

  #t
  tab_indicator_styler: ^2.0.0

  #u
  url_launcher: ^6.0.7

  #w
  wechat_assets_picker: ^7.2.0





dev_dependencies:

  flutter_lints: ^1.0.0
  retrofit_generator: any
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.0
  pretty_dio_logger: ^1.1.1


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 200

flutter_native_splash:
  color: "#1174CC"

  android_12:


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/ic_launcher.png"

#  flutter pub get
#  flutter pub run flutter_launcher_icons:main